deployment:
  tasks:
    - export DEPLOYPATH=/home/ep3s6easy863/admin.syvec.com.pe/
    - /bin/rsync -a --exclude 'index.php' public/ $DEPLOYPATH
    - ssh ep3s6easy863@72.167.76.150 'cd /home/ep3s6easy863/admin.syvec.com.pe/ && php artisan storage:link'